language: python
matrix:
  include:
    - name: Python 3.7 on Linux
      python: 3.7
      os: linux
    - name: Python 3.8 on Linux
      python: 3.8
      os: linux
    - name: Python Nightly on Linux
      python: nightly
      os: linux
    - name: Python 3.7 on Windows
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7.6
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:/c/tools/bin:$PATH**
    - name: Python 3.8 on Windows
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.8.1
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:/c/tools/bin:$PATH**
    - name: Python Pre on Windows
      language: shell
      os: windows
      before_install:
        - choco install python --pre
      env:
        - PATH=/c/Python39:/c/Python39/Scripts:/c/tools/bin:$PATH**
install:
  - pip install -r requirements.txt
script:
  - pytest
  - pylint pygot tests
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
